from .location import RetinalFieldLocationTemplate, RelativeFieldLocationTemplate, \
    RetinalFieldLocationCatTemplate, OpticDiskTemplate, RetinalFieldLocationWingTemplate
from .location_from_table import RetinalFieldLocationFromTableTemplate, RetinalFieldLocationTableParamsTemplate
from .roi_location import RelativeRoiLocationTemplate, RetinalRoiLocationTemplate
